import type { Asset } from './types';

// Mock data for the Assets sub-panel. Chiller Unit A matches the design
// reference exactly; the others use plausible defaults. Real-data swap-point
// is the getAssets() function at the bottom.
const MOCK_ASSETS: Asset[] = [
  {
    id: 'asset-001',
    name: 'Chiller Unit A',
    status: 'active',
    category: 'HVAC',
    location: 'Mechanical Room 1',
    lastServiceDate: 'Apr 15, 2026',
    commentCount: 2,
    type: 'Chiller',
    trade: 'Mechanical',
    code: 'CHU.A.001',
    description:
      'Primary air-cooled scroll chiller providing chilled water to the data hall cooling loop. Capacity: 250 tons. Operating since 2021 with no major service incidents.',
    projectLocation: 'Mechanical Room 1 · Level B1',
    latitude: '30.2672° N',
    longitude: '97.7431° W',
    photos: [],
    favorite: true,
    manufacturer: 'Carrier',
    model: '30XA-1002',
    serialNumber: 'SN-CRR-20198842',
    barcode: '0123456789012',
    installationDate: 'Mar 12, 2021',
    warrantyStartDate: 'Mar 12, 2021',
    warrantyExpiryDate: 'Mar 12, 2026',
    maintenanceSchedule: 'Quarterly',
    vendor: 'Miller MEP Inc.',
    nextServiceDate: 'Jul 15, 2026',
    specialtyContractor: {
      name: 'Miller MEP Inc.',
      initials: 'MM',
      trade: 'Mechanical',
      category: 'HVAC',
      rating: 4.7,
      address: '4825 Industrial Blvd · Austin, TX 78745',
      phone: '+1 (512) 555-0188',
      website: 'millermep.com',
      license: 'TACLA #M-0042918',
      contractValue: '$184,500',
      onProject: '4 years',
      primaryContact: {
        initials: 'TB',
        name: 'Tara Brennan',
        title: 'Senior Project Engineer · Commissioning',
        phone: '+1 (512) 555-0146',
        email: 'tbrennan@millermep.com',
      },
    },
    linkedElementId: '100',
  },
  {
    id: 'asset-002',
    name: 'Chiller Unit B',
    status: 'in-repair',
    category: 'HVAC',
    location: 'Mechanical Room 1',
    lastServiceDate: 'Mar 3, 2026',
    commentCount: 8,
    type: 'Chiller',
    trade: 'Mechanical',
    code: 'CHU.B.002',
    description:
      'Backup air-cooled scroll chiller serving the data hall cooling loop. Currently down for compressor replacement; expected return to service end of month.',
    projectLocation: 'Mechanical Room 1 · Level B1',
    latitude: '30.2672° N',
    longitude: '97.7431° W',
    photos: [],
    favorite: false,
    linkedElementId: '150',
  },
  {
    id: 'asset-003',
    name: 'Pump Station P-1',
    status: 'active',
    category: 'Plumbing',
    location: 'Basement Level 1',
    lastServiceDate: 'May 2, 2026',
    commentCount: 0,
    type: 'Pump',
    trade: 'Plumbing',
    code: 'PMP.P1.003',
    description: 'Domestic cold-water booster pump station feeding levels 1–4.',
    projectLocation: 'Basement Level 1',
    photos: [],
    favorite: false,
    linkedElementId: '250',
  },
  {
    id: 'asset-004',
    name: 'Cooling Tower CT-1',
    status: 'active',
    category: 'HVAC',
    location: 'Roof Level',
    lastServiceDate: 'Apr 28, 2026',
    commentCount: 1,
    type: 'Cooling Tower',
    trade: 'Mechanical',
    code: 'CT.001',
    description:
      'Open-circuit cooling tower providing condenser water rejection for the chiller plant. 500 ton capacity.',
    projectLocation: 'Roof Level',
    photos: [],
    favorite: false,
    linkedElementId: '320',
  },
  {
    id: 'asset-005',
    name: 'Server Room AHU',
    status: 'active',
    category: 'HVAC',
    location: 'Server Room',
    lastServiceDate: 'May 10, 2026',
    commentCount: 3,
    type: 'Air Handler',
    trade: 'Mechanical',
    code: 'AHU.SR.005',
    description: 'Dedicated air handler conditioning the server room with N+1 redundancy.',
    projectLocation: 'Server Room · Level 2',
    photos: [],
    favorite: false,
    linkedElementId: '400',
  },
  {
    id: 'asset-006',
    name: 'Boiler B-1',
    status: 'active',
    category: 'HVAC',
    location: 'Mechanical Room 2',
    lastServiceDate: 'Feb 18, 2026',
    commentCount: 0,
    type: 'Boiler',
    trade: 'Mechanical',
    code: 'BLR.001',
    description: 'High-efficiency condensing boiler serving the heating hot-water loop.',
    projectLocation: 'Mechanical Room 2 · Level B1',
    photos: [],
    favorite: false,
    linkedElementId: '500',
  },
  {
    id: 'asset-007',
    name: 'Electrical Panel EP-3',
    status: 'in-repair',
    category: 'Electrical',
    location: 'Electrical Room',
    lastServiceDate: 'Jan 22, 2026',
    commentCount: 4,
    type: 'Distribution Panel',
    trade: 'Electrical',
    code: 'EP.003',
    description: 'Branch distribution panel feeding mechanical room loads.',
    projectLocation: 'Electrical Room · Level B1',
    photos: [],
    favorite: false,
    linkedElementId: '620',
  },
  {
    id: 'asset-008',
    name: 'Backup Generator',
    status: 'active',
    category: 'Electrical',
    location: 'Generator Room',
    lastServiceDate: 'Apr 5, 2026',
    commentCount: 1,
    type: 'Generator',
    trade: 'Electrical',
    code: 'GEN.001',
    description: 'Diesel standby generator, 750 kVA, supporting critical loads.',
    projectLocation: 'Generator Room · Exterior Pad',
    photos: [],
    favorite: false,
    linkedElementId: '740',
  },
  {
    id: 'asset-009',
    name: 'Fire Pump FP-1',
    status: 'active',
    category: 'Fire Protection',
    location: 'Fire Pump Room',
    lastServiceDate: 'Mar 30, 2026',
    commentCount: 0,
    type: 'Fire Pump',
    trade: 'Fire Protection',
    code: 'FP.001',
    description: 'Electric-driven fire pump serving the building sprinkler system.',
    projectLocation: 'Fire Pump Room · Level B1',
    photos: [],
    favorite: false,
    linkedElementId: '850',
  },
  {
    id: 'asset-010',
    name: 'Air Handler AH-2',
    status: 'active',
    category: 'HVAC',
    location: 'Penthouse',
    lastServiceDate: 'Apr 12, 2026',
    commentCount: 2,
    type: 'Air Handler',
    trade: 'Mechanical',
    code: 'AHU.002',
    description: 'Roof-mounted air handler serving levels 5–8.',
    projectLocation: 'Penthouse · Roof Level',
    photos: [],
    favorite: false,
    linkedElementId: '960',
  },
  {
    id: 'asset-011',
    name: 'Domestic Water Tank',
    status: 'inactive',
    category: 'Plumbing',
    location: 'Roof Level',
    lastServiceDate: 'Dec 1, 2025',
    commentCount: 5,
    type: 'Storage Tank',
    trade: 'Plumbing',
    code: 'TNK.DOM.011',
    description: 'Domestic water storage tank, currently taken out of service for liner replacement.',
    projectLocation: 'Roof Level',
    photos: [],
    favorite: false,
    linkedElementId: '1080',
  },
  {
    id: 'asset-012',
    name: 'Exhaust Fan EF-4',
    status: 'active',
    category: 'HVAC',
    location: 'Kitchen',
    lastServiceDate: 'May 18, 2026',
    commentCount: 0,
    type: 'Exhaust Fan',
    trade: 'Mechanical',
    code: 'EF.004',
    description: 'Kitchen hood exhaust fan with grease filtration.',
    projectLocation: 'Kitchen · Level 1',
    photos: [],
    favorite: false,
    linkedElementId: '1200',
  },
];

export function getAssets(): Promise<Asset[]> {
  return Promise.resolve(MOCK_ASSETS);
}

export function getAssetById(id: string): Promise<Asset | undefined> {
  return Promise.resolve(MOCK_ASSETS.find((a) => a.id === id));
}
